version: "3.9"
services:
  base:
    build: .
    volumes:
      - ".:/app"

  dev:
    extends:
      service: base
    command: "bash"

  deploy_base:
    build: 
      context: .
      dockerfile: deploy.dockerfile
    volumes:
      - ".:/app"
      - "~/.azure:/tmp/.azure"
    environment:
      AZURE_CONFIG_DIR: /tmp/.azure
      LOGIN_SERVER:
      LOCATION:
      RESOURCE_GROUP_NAME:
      REGISTRY_NAME:
      IMAGE_NAME:
      IMAGE_VERSION:
